name: Build and Push TrainingPortal Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: trainingportal
          file: trainingportal/Dockerfile.trainingportal
          push: true
          tags: ${{ secrets.ECR_ARN }}:${{ github.sha }}
